services:
  frontend:
    image: oven/bun:latest
    working_dir: /app
    command:
      [
        "bun","dev","--host","0.0.0.0"
      ]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 500M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.routers.frontend.rule=Host(`infokes.docker.localhost`)"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    environment:
      - TZ=Asia/Jakarta
    networks:
      base-net:
        aliases:
          - frontend
    volumes:
      - ../../frontend:/app

  backend:
    image: oven/bun:latest
    working_dir: /app
    command:
      [
        "bun","dev"
      ]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 500M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.routers.backend.rule=Host(`backend.docker.localhost`)"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"
    environment:
      - TZ=Asia/Jakarta
    networks:
      base-net:
        aliases:
          - backend
    volumes:
      - ../../backend:/app

networks:
  base-net:
    external: true
    name: base-net
