################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################

# EntryPoints definition
#
# Optional
#
entryPoints:
  web:
    address: :80

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
log:
  level: "DEBUG"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
#
# Optional
#
api:
  dashboard: false
  insecure: false

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
#
# Optional
#
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

################################################################
# ACME (Let's Encrypt) configuration
################################################################

# Enable ACME (Let's Encrypt) - using cert-manager
#
# Optional
#
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: "dev@keluargaallah.com"
#       storage: "/etc/traefik/acme.json"
#       httpChallenge:
#         entryPoint: web-unsecure
